/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelRouteImport } from './routes/panel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/batches' | '/login' | '/panel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/batches' | '/login' | '/panel'
  id: '__root__' | '/' | '/batches' | '/login' | '/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  LoginRoute: LoginRoute,
  PanelRoute: PanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
